asciidoc:
  extensions:
    - asciidoctor-kroki
site:
  title: my docs
  start_page: mydocs::index.adoc
  robots: disallow
content:
  sources:
  - url: .
    start_path: docs
    branches: master
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./custom-modules/supplemental-ui
output:
  clean: true
  dir: ./public
